### PR TITLE
Feat: Added dark theme toggle  #15

### LINKED ISSUE #15: Add Dark Theme toggle
I want to add a toggle to swap the website to a dark theme. There could also be an option to match the system theme too

### PR DESCRIPTION
**Pull request by Aniket762**
@yyjlincoln  and I have worked together on this PR. In this, we have added a toggle button that gives 3 options light mode, dark mode, and auto which displays according to the system preference. 

A glimpse of our work: [Demo](https://youtu.be/1xv1J13I970) Credit goes to @yyjlincoln for this! 

Features:
- The support of auto|light|dark
- Smooth transition between states
- No eye-blinding flash when switching pages
- When set to auto, it can listen to your phone's dark mode events and adjust its color scheme automatically
- Written in vanilla javascript, no additional libraries are used
- Flexible/modular design with functions such as `beforeModeChange` and `afterModeChange`, meaning that you can easily add more functionality to it.

- [X] My Pod Leader knows I'm working on this Pull Request
- [X] I've explained what the Pull Request is adding.
- [X] I've explained why this is important.

This pull request closes #15

### CODE REVIEW

**Review by yyjlincoln — APPROVED** [review]
lgtm

**Comment by yyjlincoln** [comment]
Closing this PR as we will need to merge another commit.

**Comment by Aniket762** [comment]
> 

Hey, why did you close this?

**Comment by yyjlincoln** [comment]
Hey, I've cleaned up some files which created another commit, meaning that this PR is no longer up to date. I'm also migrating all commits to the main repo - check your discord msg @Aniket762

**Comment by yyjlincoln** [comment]
I will be migrating our commits through #22, and then I will open another PR with reference to the latest commit soon.

**Comment by yyjlincoln** [comment]
#23

**Pull request closed without merging**
