### PR TITLE
feat: Added page transitions. [#25]

### LINKED ISSUE #25: Add some animations!
Currently, our site is a bit boring and it does not have any animations. Why don't we add one?

### PR DESCRIPTION
**Pull request by yyjlincoln**
# Feature: Added page transitions

## Intuition
It's nice to have some transitions when switching between pages - especially if the user's internet is slow & the page takes a long time to load. We don't really want them to feel they're stuck and nothing works.

## Implementation

- Framework-wise:
  - JS Hooks `beforePageTransition()` and `afterPageTransition()` (both async)
  - Dynamically (after page render) add an onClick for all `<a>`  tags (to capture the page switch)
- Design-wise:
  - Make a beautiful transition page
  - Make the transition using GSAP

## Implementation Notes
- I used GSAP, which adds 23kb (gzip+min) to the request. That's not much though.
- Feel free to make a better transition using `beforePageTransition()` and `afterPageTransition()` hooks!

## Author
- @yyjlincoln

## PR Checklist
- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

## Additional Info
This PR resolves #25.

### CODE REVIEW

**Review by anubhav06 — APPROVED** [review]
The transition looks amazing ! 🎉

**Comment by yyjlincoln** [comment]
Quick demo: https://www.youtube.com/watch?v=LB6BSgc9Ey4

**Review by ditsuke — APPROVED** [review]
LGTM! I did a little review and made some changes, please have a look to confirm they're alright 😃

**Review by gmelodie — APPROVED** [review]
Looking good!

**Comment by yyjlincoln** [comment]
> @ditsuke: LGTM! I did a little review and made some changes, please have a look to confirm they're alright 😃

Thanks a lot for cleaning up the code!

**Pull request merged**
