### PR TITLE
Use the same navigation bar throughout the website

### PR DESCRIPTION
**Pull request by yyjlincoln**
Now using the same nav bar throughout the website to ensure consistent user experience.

Check the preview for more info.

- [ ] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by adizcode** [comment]
LGTM!

**Review by ditsuke — APPROVED** [review]
Nice work!

**Comment by ditsuke** [comment]
@adizcode I think you missed approving it in the review mode. Could you do that so we can merge this one then 😄

**Review by Dhruv-Sachdev1313 — APPROVED** [review]
Looks really Nice!!

**Comment by ditsuke** [comment]
2 approvals - good to go! Nice work @yyjlincoln 😄

**Comment by adizcode** [comment]
@ditsuke yea my bad. 😅

**Pull request merged**
