### PR TITLE
enhancement: Add a navigation bar

### LINKED ISSUE #9: Add a navigation bar
As the portfolio gains more information, it may make sense to add a navigation bar. This bar should include the logo on the left side but only once the page has scrolled down a bit.

### PR DESCRIPTION
**Pull request by adizcode**
# Context
- To add the navigation bar for the project.
- Closes #9 

## Implementation
- Added Sass and JavaScript code to make the navigation bar sticky and dynamic
- Link to navigation bar items to appropriate sections.

## Authors
@adizcode and @harshsharma6401

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Review by gmelodie — CHANGES_REQUESTED** [review]
The code itself is good, but there are a couple things I'd expect to work differently here:
1. The navigation bar goes behind some elements like here:
image

2. The bar should be consistent, meaning it should be the same bar we see when we land in the page, and it just scrolls with us when we go down the page. The way it is right now, you can only see the `Meet the pod` and `Projects` buttons if you scroll down.

**Comment by adizcode** [comment]
> The code itself is good, but there are a couple things I'd expect to work differently here:
> 
>     1. The navigation bar goes behind some elements like here:
>        image
> 
>     2. The bar should be consistent, meaning it should be the same bar we see when we land in the page, and it just scrolls with us when we go down the page. The way it is right now, you can only see the `Meet the pod` and `Projects` buttons if you scroll down.

Thank you for the feedback. We'll work on this!

**Review by anubhav06 — CHANGES_REQUESTED** [review]
The header looks great, but the `Meet the Pod` and `Projects` link doesn't work.

**Comment by yyjlincoln** [comment]
> The header looks great, but the `Meet the Pod` and `Projects` link doesn't work. 

That's an issue with page-transitions.I will fix it now.

**Review by anubhav06 — APPROVED** [review]
Perfect! 🎉

**Comment by yyjlincoln** [comment]
Please don't add:
```
html {
    scroll-behavior: smooth;
}
```
The scrolling is implemented in JavaScript and adding that scroll-behavior property will cause some unexpected effects. I've removed it while resolving the merge conflict.

**Review by yyjlincoln — COMMENTED** [review]
Great work! I trust that you can fix it

**Comment by adizcode** [comment]
> I trust that you can fix it! I'll have another look after the next meeting

Thanks :D

**Review by KshitijDarekar — COMMENTED** [review]
Looks Good to me.

**Review by yyjlincoln — APPROVED** [review]
Great fix!

**Comment by yyjlincoln** [comment]
Don't know why CI is failing.
> Error: 'main' branch not found.
What??

**Comment by yyjlincoln** [comment]
I'll try and merge this - not really sure if the contribution count github action will work on a PR

**Comment by adizcode** [comment]
> Don't know why CI is failing.
> > Error: 'main' branch not found.
> 
> What??

It's the same with #50
That's the weirdest error I've ever come across lol

Could be an issue with the CI itself

**Pull request merged**
