### PR TITLE
Issue#3 Improve loading time for images by Compressing 

### PR DESCRIPTION
**Pull request by KshitijDarekar**
## Summary
- Used  [Github Image Actions](https://github.com/marketplace/actions/image-actions) to optimize images
- Added  `.github/workflows/calibreapp-image-actions.yml` in the repository
- Image Actions will compress images so that they’re smaller, every time we push an image in the main branch,
- We can control the quality of the images, we have kept it to default as of now
- Image Actions adds optimized images to the current Pull Request and posts a summary comment.

     #### Image Actions will run in the following scenarios:

 - on Pull Requests containing images (not including forks)
 - on pushing of images to `main` (for forks)
 - on schedule at 11 PM every Sunday(we can change the days and timing) if anything gets missed with any of the above scenarios

## Screenshots
Demo Test: In a forked repository, we created a separate branch, added an image, and pushed it to the main branch of the forked repo. So while making the PR the images are optimized.
test2

## Author
@KshitijDarekar @psahithireddy 

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

## References and Resources

- https://github.com/calibreapp/image-actions
- https://github.com/marketplace/actions/image-actions
- https://github.com/marketplace/actions/image-optimizer

## Additional Info
This PR closes [issue#3](https://github.com/MLH-Fellowship/jan-2022-prep-portfolio/issues/3)

### CODE REVIEW

**Comment by yyjlincoln** [comment]
Great work. I have a question though - will Github Action compress an already-compressed image? If it's going to compress all images every Sunday at 11 pm then the image quality might be really bad after a few compressions.

**Comment by KshitijDarekar** [comment]
I supposed it should not compress an already compressed image as when we made a PR (in the forked repo)it mentioned that the 2 images did not require optimization. But I will verify it again.

**Comment by ditsuke** [comment]
Should we have cron at all? Maybe it's enough to have it run on pushes and PRs.

**Comment by KshitijDarekar** [comment]
Perhaps we would be fine without a cron job as well. Although in the case of push and PR the changes should include an update in the imagery (i.e addition or deletion of an image file), for Image Actions to optimize.Open to suggestions.

**Comment by KshitijDarekar** [comment]
Image-actions does not store state information about images, they're always compressed — if there's a significant improvement (more than -1%), the image will be committed, otherwise ignored.
That way, if subsequent commits update the same image, it'll be reevaluated and committed if need be.

Source :
https://github.com/calibreapp/image-actions/issues/23

**Comment by yyjlincoln** [comment]
I don't think we'll need cron. With cron, the image will be repeatedly compressed until its quality is so bad that compressing it again doesn't make much of a difference (i.e. <1% improvement). I might be wrong though but at least that's my understanding.

Compressing the images on `push to main` and (`PR` | `merge`) will be sufficient as there's no other way we can introduce an image to our repo. After deploying this, we might want to manually trigger the action once to compress existing images in our repo.

**Comment by KshitijDarekar** [comment]
> I don't think we'll need cron. With cron, the image will be repeatedly compressed until its quality is so bad that compressing it again doesn't make much of a difference (i.e. <1% improvement). I might be wrong though but at least that's my understanding.
> 
> Compressing the images on `push to main` and (`PR` | `merge`) will be sufficient as there's no other way we can introduce an image to our repo. After deploying this, we might want to manually trigger the action once to compress existing images in our repo.
> 
> @ditsuke @KshitijDarekar What do you think?
> 
> _I'm going to bed now - just merge it if you agree with me, otherwise we can discuss when I wake up_

Alright, @ditsuke  what do u suggest ?Should we remove the cron job or not ?

**Comment by psahithireddy** [comment]
I think lets remove it.If any PRs have images it will automatically work on them, so I don't think we need a corn job, especially when we are not very sure of it

**Comment by ditsuke** [comment]
> > I don't think we'll need cron. With cron, the image will be repeatedly compressed until its quality is so bad that compressing it again doesn't make much of a difference (i.e. <1% improvement). I might be wrong though but at least that's my understanding.
> > 
> > Compressing the images on `push to main` and (`PR` | `merge`) will be sufficient as there's no other way we can introduce an image to our repo. After deploying this, we might want to manually trigger the action once to compress existing images in our repo.
> > 
> > @ditsuke @KshitijDarekar What do you think?
> > 
> > _I'm going to bed now - just merge it if you agree with me, otherwise we can discuss when I wake up_
> 
> Alright, @ditsuke  what do u suggest ?Should we remove the cron job or not ?
> 

I think we should remove it!

**Comment by yyjlincoln** [comment]
Let's remove it and get it merged

**Review by adizcode — APPROVED** [review]

**Pull request merged**
