### PR TITLE
Added Map

### PR DESCRIPTION
**Pull request by Dhruv-Sachdev1313**
## Please, go through these steps before you submit a PR.
Added Map with @VaibhaveS 
This is the same PR that was reviewed before, I think it is okay to merge it!

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Review by ditsuke — APPROVED** [review]

**Comment by ditsuke** [comment]
Good to merge 👍

**Comment by VaibhaveS** [comment]
Just a minute, tushar's info is there twice

**Comment by Dhruv-Sachdev1313** [comment]
> Just a minute, tushar's info is there twice

Ohh God 🙈

**Review by yyjlincoln — COMMENTED** [review]
Nice work!

**Pull request merged**
